# Treinar um modelo de regressão linear em n dimensões

In [ ]:
import numpy as np
X = np.array([[1, 1, 3], [1, 2, 1], [2, 2, 4], [2, 3, 5]])
# y = 1 * x_1 + 2 * x_2 + 5 * x_3 + 3
y = np.dot(X, np.array([1, 2, 5])) + 3

In [ ]:
X[:5]

array([[1, 1, 3],
       [1, 2, 1],
       [2, 2, 4],
       [2, 3, 5]])

In [ ]:
y[:5]

array([21, 13, 29, 36])

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, y)

In [ ]:
print(reg.coef_)

print(reg.intercept_)

[1. 2. 5.]
3.000000000000007


In [ ]:
reg.predict(np.array([[1, 2, 3]]))

array([23.])

In [ ]:
X_test = np.array([[1, 2, 3], [8, 9, 10], [2, 2, 4]])
y_pred = reg.predict(X_test)
y_pred

array([23., 79., 29.])

In [ ]:
y_true = np.dot(X_test, np.array([1, 2, 5])) + 3
y_true

array([23, 79, 29])

# Salvar o modelo Scikit-Learn

In [ ]:
import joblib
filename = "reg.joblib"
joblib.dump(reg, filename)

['reg.joblib']

In [ ]:
loaded_reg = joblib.load(filename)
loaded_reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Carregar e reutilizar o modelo Scikit-Learn

In [ ]:
y_pred = loaded_reg.predict(X_test)

In [ ]:
y_pred

array([23., 79., 29.])